[book]
authors = ["Lachlan Sneff"]
language = "en"
multilingual = false
src = "src"
title = "lachlan sneff's lab notebook"

[rust]
edition = "2018"

[build]
create-missing = false

[output.html]
default-theme = "rust"
mathjax-support = true
git-repository-url = "https://github.com/lachlansneff/lab"
cname = "lab.charted.space"
additional-css = ["toc.css"]

[preprocessor.preprocess]
command = "cargo run --manifest-path preprocess/Cargo.toml"
renderer = ["html"]
